### ISSUE TITLE
kubecm ls filter 

### ISSUE THREAD

**Issue by cynial** [sunny0826/kubecm#11]
不知道能不能支持，根据自定义的 filter ，过滤某些集群？

**Comment by sunny0826** [comment]
好主意，我考虑一下怎么实现

**Comment by sunny0826** [comment]
@cynial 能详细描述下您希望使用什么样的过滤规则吗？如`dev-`开头，或 `-test`后缀？

**Comment by cynial** [comment]
我这边是希望能过滤 NAME 字段，比如我现在管理着 30 多个集群，我想看：

1、部署在深圳 shenzhen 的有哪些集群
2、测试集群 test 分别在哪些地方部署了

NAME
w-test-shenzhen-mz
w-test-tianjin-mz
w-test-beijing-mz
w-prod-tianjin-mz
w-prod-beijing-mz

**Comment by sunny0826** [comment]
只要包含该关键字，如：
```bash
$ kubecm ls --filter shenzhen
NAME
w-test-shenzhen-mz
```

**Comment by sunny0826** [comment]
this feature is released, please use [v0.13.0]https://github.com/sunny0826/kubecm/releases/tag/v0.13.0
