### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mogu1986** [sunny0826/kubecm#15]
初次使用，添加一个config成功后，再次添加开始报错，kubecm ls也报，如下：

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ea0aa5]

goroutine 1 [running]:
github.com/sunny0826/kubecm/cmd.Formatable(0xc0002d2c50, 0xc000127d58)
	/github/workspace/cmd/utils.go:97 +0x285
github.com/sunny0826/kubecm/cmd.(*ListCommand).runList(0xc0002bf570, 0xc000263b80, 0x2b28a18, 0x0, 0x0, 0x0, 0x0)
	/github/workspace/cmd/list.go:30 +0x26
github.com/sunny0826/kubecm/cmd.(*ListCommand).Init.func1(0xc000263b80, 0x2b28a18, 0x0, 0x0, 0x0, 0x0)
	/github/workspace/cmd/list.go:22 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000263b80, 0x2b28a18, 0x0, 0x0, 0xc000263b80, 0x2b28a18)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002622c0, 0x10449b7, 0x2a847a0, 0xc000058778)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/github/workspace/main.go:27 +0x36

**Comment by sunny0826** [comment]
请问使用的是哪个版本？

**Comment by mogu1986** [comment]
感谢回复。

Version: 0.12.0
GoOs: darwin
GoArch: amd64

**Comment by sunny0826** [comment]
这个问题已经发现了，后续版本会修复，感谢反馈

**Comment by sunny0826** [comment]
this bug is fixed, please use [v0.13.0](https://github.com/sunny0826/kubecm/releases/tag/v0.13.0)

**Comment by mogu1986** [comment]
ok , thx  :)
