### ISSUE TITLE
更新到最新版本后merge错误

### ISSUE THREAD

**Issue by MiiW** [sunny0826/kubecm#19]
![image](https://user-images.githubusercontent.com/17247982/102196139-745e1100-3efa-11eb-99b4-b8f256770500.png)
更新到最新版本后，不支持merge的-c参数了。去除-c参数，合并后kubeconfig是错的，server全是一个。查了下合并后的kubeconfig，确实不对。

**Comment by sunny0826** [comment]
merge 的 -c 参数被移除了，现在回跳出问答框询问是否覆盖，合并的这个问题我再看一下

**Comment by MiiW** [comment]
> merge 的 -c 参数被移除了，现在回跳出问答框询问是否覆盖，合并的这个问题我再看一下

我拉了源代码编译了，似乎是重构之后引入的，回退掉就正常了。

**Comment by sunny0826** [comment]
This feature has been released at [v0.14.0](https://github.com/sunny0826/kubecm/releases/tag/v0.14.0)
