### ISSUE TITLE
MAC 安装报错

### ISSUE THREAD

**Issue by Eddie-he** [sunny0826/kubecm#2]
brew install sunny0826/tap/kubecm
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
arduino-cli                    jenkins                        nim                            open-babel                     phpunit                        watchexec
==> minikube has been moved to Homebrew.
To uninstall the cask run:
  brew cask uninstall --force minikube
==> Installing minikube...
==> Downloading https://homebrew.bintray.com/bottles/minikube-1.5.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/15/157d59038a69e69178185216cf9bc0f06f7d029ed31ee8598da72f98f367b86c?__gda__=exp=1572328857~hmac=03e5fe9aa36d09059156d2b88ec1cb224143d5f0
######################################################################## 100.0%
==> Pouring minikube-1.5.0.mojave.bottle.tar.gz
==> minikube cask is installed, skipping link.
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/minikube/1.5.0: 8 files, 61.1MB
Linking /usr/local/Cellar/minikube/1.5.0... 3 symlinks created

==> Tapping sunny0826/tap
Cloning into '/usr/local/Homebrew/Library/Taps/sunny0826/homebrew-tap'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/sunny0826/homebrew-tap/kubecm.rb
kubecm: undefined method `updatetime' for #<Class:0x00007fc9ce29a500>
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/sunny0826/homebrew-tap/hamal.rb
hamal: undefined method `updatetime' for #<Class:0x00007fc9ce298638>
Error: Cannot tap sunny0826/tap: invalid syntax in tap!

**Comment by sunny0826** [comment]
@Eddie-he 已修复
