### ISSUE TITLE
[bug] fish shell completion throw error

### ISSUE THREAD

**Issue by sunny0826** [sunny0826/kubecm#272]
@sunny0826 Tested and still having the issue.

Builded using a clean Linux env and a fresh fish installation:

`vscode@a71fb1df192a /w/kubecm (dependabot/go_modules/github.com/spf13/cobra-1.4.0)> ./kubecm math: Error: Unexpected tokenish/completions/kubecm.fish
'ompletion ended with directive: ShellCompDirectiveNoFileComp / 1'
         ^
math: Error: Unexpected token
'% 2'
 ^
test: Missing argument at index 2

~/.config/fish/completions/kubecm.fish (line 93): 
    if test $compErr -eq 1
       ^
in function '__kubecm_prepare_completions'
in command substitution

(Type 'help test' for related documentation)
math: Error: Unexpected token
'ompletion ended with directive: ShellCompDirectiveNoFileComp / 8'
         ^
math: Error: Unexpected token
'% 2'
 ^
math: Error: Unexpected token
'ompletion ended with directive: ShellCompDirectiveNoFileComp / 16'
         ^
math: Error: Unexpected token
'% 2'
 ^
test: Missing argument at index 2

~/.config/fish/completions/kubecm.fish (line 101): 
    if test $filefilter -eq 1; or test $dirfilter -eq 1
       ^
in function '__kubecm_prepare_completions'
in command substitution

(Type 'help test' for related documentation)
test: Missing argument at index 2

~/.config/fish/completions/kubecm.fish (line 101): 
    if test $filefilter -eq 1; or test $dirfilter -eq 1
                                  ^
in function '__kubecm_prepare_completions'
in command substitution

(Type 'help test' for related documentation)
math: Error: Unexpected token
'ompletion ended with directive: ShellCompDirectiveNoFileComp / 2'
         ^
math: Error: Unexpected token
'% 2'
 ^
math: Error: Unexpected token
'ompletion ended with directive: ShellCompDirectiveNoFileComp / 4'
         ^
math: Error: Unexpected token
'% 2'
 ^
test: Missing argument at index 2

~/.config/fish/completions/kubecm.fish (line 117): 
    if test $nospace -ne 0; or test $nofiles -eq 0
       ^
in function '__kubecm_prepare_completions'
in command substitution

(Type 'help test' for related documentation)
test: Missing argument at index 2

~/.config/fish/completions/kubecm.fish (line 117): 
    if test $nospace -ne 0; or test $nofiles -eq 0
                               ^
in function '__kubecm_prepare_completions'
in command substitution

(Type 'help test' for related documentation)`

The same results using MacOs

_Originally posted by @interpeix in https://github.com/sunny0826/kubecm/issues/76#issuecomment-1080265885_

**Comment by sunny0826** [comment]
@interpeix This issue has been fixed in [0.16.4](https://github.com/sunny0826/kubecm/releases/tag/v0.16.4), can you help to verify that I don't have a filsh environment locally?

**Comment by interpeix** [comment]
@sunny0826 awesome! Totally fixed, thanks for the support.
