### ISSUE TITLE
kubecm delete interactively exit.

### ISSUE THREAD

**Issue by chenyg0911** [sunny0826/kubecm#4]
Thank you for the great tool!
But, when I run `kubecm delete`, if I don't want delete a context, the tools can't exit as normal. I've to press 'ctrl+c'. Just some inconvenience.

**Comment by sunny0826** [comment]
Maybe I can add an exit option to option `delete` &`rename`

**Comment by sunny0826** [comment]
This feature has been added in [v0.7.4](https://github.com/sunny0826/kubecm/releases/tag/v0.7.4).
