### ISSUE TITLE
Merge config file failed

### ISSUE THREAD

**Issue by SliverYuki** [sunny0826/kubecm#46]
![image](https://user-images.githubusercontent.com/19161689/122898510-84f5b500-d37d-11eb-8084-25aa71544205.png)
please take a look

**Comment by sunny0826** [comment]
Please remove `.DS_Store` file in  `all_config`

**Comment by SliverYuki** [comment]
> Please remove `.DS_Store` file in `all_config`

Thank you very much for your prompt reply！Now it working good.
