### ISSUE TITLE
Support manage kubeconfig with AWS EKS

### ISSUE THREAD

**Issue by sunny0826** [sunny0826/kubecm#49]
refer #44

**Comment by AdamRussak** [comment]
we can talk if you want, me cli tool is doing just that.
https://github.com/AdamRussak/k8f

**Comment by sunny0826** [comment]
If you can contribute this part of the code, I would be very grateful. 🎉

You can find the relevant code [here](https://github.com/sunny0826/kubecm/blob/master/cmd/cloud_add.go), and if you have any questions, feel free to contact me at any time.

**Comment by AdamRussak** [comment]
what is the vision here?
adding 1 cluster in a cloud provider?
or scanning and adding all of them dynamically? (wich my tool [k8s](https://github.com/AdamRussak/k8f) is doing)

**Comment by sunny0826** [comment]
Well. I use this feature quite often. I usually use Terraform to batch create k8s clusters, and using `kubecm cloud` allows me to download and merge the kubeconfig of the cluster I need to use into my local Kubeconfig without logging into the Cloud UI.

There is a difference between this and dynamically adding all clusters, where I just add the clusters of my choice.
