### ISSUE TITLE
feature request: switch default namespace.

### ISSUE THREAD

**Issue by chenyg0911** [sunny0826/kubecm#5]
I usually use kucectx and kubens to switch default context and default namespace.
Now kubecm support switch context, I hope it can support switch default namespace.
BTW, swictch command can;t support more sub-command to quickly switch with context name.
just like `kubecm switch my-context`.

**Comment by sunny0826** [comment]
This is a good idea.let me try.

**Comment by sunny0826** [comment]
@chenyg0911 Sorry to reply so long, these problems will be developed after the Chinese New Year.

**Comment by sunny0826** [comment]
This feature has been added in [v0.8.0](https://github.com/sunny0826/kubecm/releases/tag/v0.8.0).

**Comment by chenyg0911** [comment]
Thanks!
