### ISSUE TITLE
Need to change the tar name format to make it consistent with the `.krew.yaml`

### ISSUE THREAD

**Issue by astraw99** [sunny0826/kubecm#510]
**Describe the bug**
In the .krew.yaml, the release download url is:
```
https://github.com/sunny0826/kubecm/releases/download/{{ .TagName }}/kubecm_{{ .TagName }}_Linux_x86_64.tar.gz
```

But currently, our release url is:
```
https://github.com/sunny0826/kubecm/releases/download/v0.19.3/kubecm_0.19.3_Linux_x86_64.tar.gz
```

So we need to change the `kubecm_0.19.3` to `kubecm_v0.19.3` to make it consistent.

**Comment by sunny0826** [comment]
It has been modified in [v0.19.3](https://github.com/sunny0826/kubecm/releases/tag/v0.19.3), and the configuration in `goreleaser` will be modified later.

**Comment by astraw99** [comment]
Cool, thanks~

**Comment by sunny0826** [comment]
`goreleaser` configuration file has been updated in #511 .
