### ISSUE TITLE
binary naming convention

### ISSUE THREAD

**Issue by Shikachuu** [sunny0826/kubecm#513]
# Description
Noticed that the binary naming is changed since the last release, from `kubecm_0.19.2_Darwin_arm64.tar.gz` to `kubecm_v0.19.3_Darwin_arm64.tar.gz`, the difference is the char `v` in the version.

Was the change intentional or is it a bug?

It broke our [end-to-end test suite](https://github.com/alexellis/arkade/runs/8089334237?check_suite_focus=true#step:4:906) in [arkade](https://github.com/alexellis/arkade) which features your project.

If the change was intentional please let me know and I'll submit a PR in arkade, elsewise I'm more then happy to fix this behaviour in your project!

**Comment by sunny0826** [comment]
Sorry, I was not aware before that this would have an impact on your project. Yes, this is an intentional change and subsequent releases will be named according to this format. See #120 for the reason.

**Comment by astraw99** [comment]
It is because this plugin has been integrated into the Krew manager recently.
Also see https://github.com/sunny0826/kubecm/issues/510 for the name change reason.

**Comment by Shikachuu** [comment]
Thanks, then I'll send a PR for arkade and close this.

**Comment by alexellis** [comment]
Changing binary release names should be considered a breaking change too.

Thanks for letting us know.
