### ISSUE TITLE
Disable notifications on macOS

### ISSUE THREAD

**Issue by patricks** [sunny0826/kubecm#524]
With version [0.20.0](https://github.com/sunny0826/kubecm/tree/v0.20.0) a new feature was added to present a macOS notification if a command was successful. It would be nice, if there would be a setting to disable this feature.

The PR was: https://github.com/sunny0826/kubecm/pull/518

**Comment by sunny0826** [comment]
Of course, I will add a flag to disable this feature in the next release, and by default, the notification feature is disabled.

**Comment by sunny0826** [comment]
This issue has recently been fixed in [v0.20.1](https://github.com/sunny0826/kubecm/releases/tag/v0.20.1), so if you have other problems, please reopen it.
