### ISSUE TITLE
context name must have more than 3 characters

### ISSUE THREAD

**Issue by shaohjz** [sunny0826/kubecm#580]
why limit this feature，rename a context into less characters are more easily...
<img width="605" alt="image" src="https://user-images.githubusercontent.com/37829326/198304175-01cf2c84-a09b-4d70-983b-d0c27f4dfbff.png">

**Comment by sunny0826** [comment]
Indeed, I will recheck this feature (which was developed two years ago) and if there are no other problems, this restriction will be lifted.
