### ISSUE TITLE
Feature Request: Support override context name when add config

### ISSUE THREAD

**Issue by imroc** [sunny0826/kubecm#680]
**Is your feature request related to a problem? Please describe.**

We can not override the context name when add a config:

```bash
kubecm add -cf myconfig
```
So we need to rename context after add every time, make it hard to use in automation script.

**Describe the solution you'd like**

Support `--context-name` flag to override context name, just like what [kconf](https://github.com/particledecay/kconf) did.

**Comment by sunny0826** [comment]
Great idea! This feature does not seem to be difficult to implement, and I will add this feature as soon as possible.

**Comment by sunny0826** [comment]
This feature has been released in [0.23.0](https://github.com/sunny0826/kubecm/releases/tag/v0.23.0)
