### ISSUE TITLE
Asset names for v0.24.0 got broken

### ISSUE THREAD

**Issue by suzuki-shunsuke** [sunny0826/kubecm#720]
Asset names for v0.24.0 got broken.

https://github.com/sunny0826/kubecm/releases/tag/v0.24.0

```
kubecm_.0.24.0_Darwin_arm64.tar.gz
kubecm_.0.24.0_Darwin_x86_64.tar.gz
kubecm_.0.24.0_Linux_arm64.tar.gz
kubecm_.0.24.0_Linux_i386.tar.gz
kubecm_.0.24.0_Linux_x86_64.tar.gz
kubecm_.0.24.0_Windows_i386.tar.gz
kubecm_.0.24.0_Windows_x86_64.tar.gz
```

<img width="1009" alt="image" src="https://github.com/sunny0826/kubecm/assets/13323303/38bfb7ab-a77e-46ff-8e56-439895c60007">

**Comment by suzuki-shunsuke** [comment]
Oh? v0.24.0 was removed. 🤔 

https://github.com/sunny0826/kubecm/releases/tag/v0.24.0

<img width="1010" alt="image" src="https://github.com/sunny0826/kubecm/assets/13323303/f5c89e47-e528-4794-89aa-112aaf9e5f9b">

**Comment by suzuki-shunsuke** [comment]
I sent a pull request.

- https://github.com/sunny0826/kubecm/pull/719

**Comment by sunny0826** [comment]
Thank you so much for your contribution!

**Comment by sunny0826** [comment]
Thank you for your contribution, [v0.24.0](https://github.com/sunny0826/kubecm/releases/tag/v0.24.0) version has been released properly.
