### ISSUE TITLE
Unable to switch to a namespace as I have no permissions to list namespaces

### ISSUE THREAD

**Issue by e-minguez** [sunny0826/kubecm#749]
**Describe the bug**
I would like to be able to switch namespaces even if I cannot list namespaces globally.

**To Reproduce**
1. Have access to a cluster where RBAC is enabled and the current role doesn't allow to list namespaces 
2. Try to switch to a namespace (not _list_ but directly switch)
3. See error

```
❯ kubecm namespace edge-github-runners
Error: namespaces is forbidden: User "u-6mbzm7knif" cannot list resource "namespaces" in API group "" at the cluster scope
Usage:
  kubecm namespace [flags]

Aliases:
  namespace, ns

Examples:

# Switch Namespace interactively
kubecm namespace
# or
kubecm ns
# change to namespace of kube-system
kubecm ns kube-system


Flags:
  -h, --help   help for namespace

Global Flags:
      --config string   path of kubeconfig (default "/Users/eminguez/.kube/config")
  -m, --mac-notify      enable to display Mac notification banner
      --ui-size int     number of list items to show in menu at once (default 4)

namespaces is forbidden: User "u-6mbzm7knif" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Expected behavior**
Even if I cannot list namespace I would like to be able to switch to that namespace I know I have permissions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
```
❯ kubecm version
Version: 0.25.0
GoOs: darwin
GoArch: arm64
```

**Smartphone (please complete the following information):**
N/A

**Additional context**

As a workaround, I use the traditional:

```
kubectl config set-context --current --namespace=<namespace>
```

**Comment by sunny0826** [comment]
From this phenomenon, you may only have operational privileges to specify namespaces, but not `List namespace` privileges.

**Comment by e-minguez** [comment]
> From this phenomenon, you may only have operational privileges to specify namespaces, but not `List namespace` privileges.

Correct.

My ask is to avoid listing namespace when specifying a namespace:

```
kubecm namespace edge-github-runners
```

This shouldn't list the namespaces, just change the kubectl context.

**Comment by sunny0826** [comment]
Indeed, this issue will be fixed.
