### ISSUE TITLE
error when creating kubeconfig in k8s v1.27.5

### ISSUE THREAD

**Issue by adl3n** [sunny0826/kubecm#788]
**Describe the bug**
Error when creating kubeconfig in k8s v1.27.5. Will there be support for creating configs in 1.27?

**To Reproduce**
1. Install kubecm with kubectl krew install kc
2. kubectl kc create

**Expected behavior**
goroutine 1 [running]:
github.com/sunny0826/kubecm/cmd.(*CreateOptions).getToken(0xc00011fc30)
        /home/runner/work/kubecm/kubecm/cmd/create.go:222 +0x1ab
github.com/sunny0826/kubecm/cmd.(*CreateCommand).runCreate(0x0?, 0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/kubecm/kubecm/cmd/create.go:78 +0x13b
github.com/sunny0826/kubecm/cmd.(*CreateCommand).Init.func1(0xc000786600?, {0x2e323c0?, 0x0?, 0x0?})
        /home/runner/work/kubecm/kubecm/cmd/create.go:41 +0x31
github.com/spf13/cobra.(*Command).execute(0xc000786600, {0x2e323c0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000578000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/kubecm/kubecm/main.go:30 +0x25

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - K8s:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sunny0826** [comment]
Hi guys, it's good to receive your feedback. The `create` command has been in an **experimental** stage due to cluster adaptation issues, and I'll be actively working to resolve this issue, but unfortunately this doesn't have a clear solution or roadmap.

**Comment by sunny0826** [comment]
Sorry k8s 1.27 is too new for me, I have no experience with that version of k8s at the moment. I don't really know the difference between it and the old version. I'll take the time to look into it after that, thanks for the feedback.

**Comment by sunny0826** [comment]
This issue has been fixed in #864 .
