### ISSUE TITLE
list按名称排序

### ISSUE THREAD

**Issue by MiiW** [sunny0826/kubecm#8]
工作用的集群比较多，一般以名称区分不同账户不同地域，所以能否在switch时按照名字排序？

**Comment by sunny0826** [comment]
这个点子非常好，但是要按什么标准排序，首字母？还是其他序号？我目前 switch 是按照 kubeconfig 内的顺序排的，默认一点个当前 context。
或者我这里可以开发一个子命令或者 flag 用于排序。

**Comment by MiiW** [comment]
> 这个点子非常好，但是要按什么标准排序，首字母？还是其他序号？我目前 switch 是按照 kubeconfig 内的顺序排的，默认一点个当前 context。
> 或者我这里可以开发一个子命令或者 flag 用于排序。

谢谢回复。

个人一件，按照kubeconfig内顺序的思路应该保持。但是我发现在kubecm merge完成的结果是按照名称进行排序过的，是否可以按照这个顺序来呢？
比如，用户在一个文件中定义了多个context，switch显示的时候，顺序和文件内的context保持一致没什么问题。而在像我一样，多个文件多个yaml的时候，merge完成后的kubeconfig希望是文件内有序，多文件按照文件名排序，这样还是能保留按照kubeconfig内顺序显示。你觉得这样可以嘛？

如果实现较为复杂的话，开发一个flag也是不错的选择。

**Comment by sunny0826** [comment]
感谢您的建议，该优化会在近期版本优化上线，敬请期待

**Comment by sunny0826** [comment]
@MiiW 尝试修改了好几次，效果都是十分理想，能详细描述一下文件的排序规则吗？

**Comment by MiiW** [comment]
> @MiiW 尝试修改了好几次，效果都是十分理想，能详细描述一下文件的排序规则吗？

![image](https://user-images.githubusercontent.com/17247982/101732386-198e7900-3af8-11eb-9711-ea1ae1b34784.png)
现在我switch的时候是这样的，不是按照首字母排序的，每次switch的时候都要慢慢上下切换寻找，因为switch本来显示的条目就不多，所以每次在几十个kubeconfig里面找想要的就很慢

**Comment by chenyg0911** [comment]
我觉得可以改一下ls命令，类似 kubecm ls *shanghai*, 结果列出匹配的context。比如楼上的就列出两个。
然后,kubecm switch sl-shanghai-ack直接切换default context。不用再选。之前我提过直接切换的issue。用上下键选效率确实不高。

**Comment by sunny0826** [comment]
> > @MiiW 尝试修改了好几次，效果都是十分理想，能详细描述一下文件的排序规则吗？
> 
> ![image](https://user-images.githubusercontent.com/17247982/101732386-198e7900-3af8-11eb-9711-ea1ae1b34784.png)
> 现在我switch的时候是这样的，不是按照首字母排序的，每次switch的时候都要慢慢上下切换寻找，因为switch本来显示的条目就不多，所以每次在几十个kubeconfig里面找想要的就很慢。
> 看你描述似乎是kubeconfig按照文件排序？我想要的加一个额外的option，然后全部按照首字母排序～

`switch` 这个可以输入 `/` ，进行搜索的，排序已经在开发了

**Comment by sunny0826** [comment]
> 我觉得可以改一下ls命令，类似 kubecm ls _shanghai_, 结果列出匹配的context。比如楼上的就列出两个。
> 然后,kubecm switch sl-shanghai-ack直接切换default context。不用再选。之前我提过直接切换的issue。用上下键选效率确实不高。

`ls` 这个已经开发好了，使用 `-s` ，输入内容，就会输出包含该内容的所有 context

**Comment by chenyg0911** [comment]
我更新一下版本试试。把-s去掉吧。跟普通shell的ls的用法一致，这样感觉更符合习惯。
排序我倒是觉得不如支持kubecm switch context实用。
再次感谢！

**Comment by sunny0826** [comment]
还没发布...

**Comment by chenyg0911** [comment]
等版本更新。 :-)

**Comment by sunny0826** [comment]
因为 `switch` 本身就自带搜索，所以我并没有支持 `kubecm switch context`  这样的用法，还要把名字拷贝过来

**Comment by chenyg0911** [comment]
![TIM截图20201210164016](https://user-images.githubusercontent.com/16010372/101748381-70e81580-3b07-11eb-9a7e-efe33ed6d212.png)
底下还要翻很多下可能才能找到。:-)

**Comment by sunny0826** [comment]
> ![TIM截图20201210164016](https://user-images.githubusercontent.com/16010372/101748381-70e81580-3b07-11eb-9a7e-efe33ed6d212.png)
> 底下还要翻很多下可能才能找到。:-)

你可以输入 `/` 来进行搜索呀

**Comment by chenyg0911** [comment]
好吧。我用成这样了。kubecm switch /eks

**Comment by MiiW** [comment]
> > > @MiiW 尝试修改了好几次，效果都是十分理想，能详细描述一下文件的排序规则吗？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17247982/101732386-198e7900-3af8-11eb-9711-ea1ae1b34784.png)
> > 现在我switch的时候是这样的，不是按照首字母排序的，每次switch的时候都要慢慢上下切换寻找，因为switch本来显示的条目就不多，所以每次在几十个kubeconfig里面找想要的就很慢。
> > 看你描述似乎是kubeconfig按照文件排序？我想要的加一个额外的option，然后全部按照首字母排序～
> 
> `switch` 这个可以输入 `/` ，进行搜索的，排序已经在开发了

好的，感谢

**Comment by sunny0826** [comment]
> 好吧。我用成这样了。kubecm switch /eks

在 `swithc` 的时候，就可以搜索的
![Uploading image.png…]()

**Comment by chenyg0911** [comment]
嗯。我理解有误.

**Comment by sunny0826** [comment]
This feature has been released at [v0.14.0](https://github.com/sunny0826/kubecm/releases/tag/v0.14.0)
