### ISSUE TITLE
Deleting context removes user even if other context is using it

### ISSUE THREAD

**Issue by lukasz-makowczynski** [sunny0826/kubecm#814]
**Describe the bug**
If there are few contexts that are using the same user, deleting one of them deletes the user.

**To Reproduce**
1. Have a contexts A and B that are using user C
2. Use delete action on A or B
3. Check config file. User C is removed.

**Expected behavior**
Users that are used in other contexts than deleted one shoud be preserved.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.250.

**Comment by sunny0826** [comment]
This issue is real and will be fixed in the latest version.

**Comment by sunny0826** [comment]
Thanks to @yardenshoham  for fixing this issue!
