### ISSUE TITLE
export kubeconfig causes nil pointer

### ISSUE THREAD

**Issue by burmanm** [sunny0826/kubecm#850]
**Describe the bug**
Trying to change namespace fails if export KUBECONFIG is used, it's not taken into account at all:

```console
➜  k8ssandra git:(helm_charts) ✗ export KUBECONFIG="/Users/michael.burman/projects/k8ssandra/kubeconfig"
➜  k8ssandra git:(helm_charts) ✗ kubectl get all                                                                       
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   14m
➜  k8ssandra git:(helm_charts) ✗ kubecm ns
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x103c53f78]

goroutine 1 [running]:
github.com/sunny0826/kubecm/cmd.(*NamespaceCommand).runNamespace(0x0?, 0x0?, {0x10540d600, 0x0, 0x0})
        github.com/sunny0826/kubecm/cmd/namespace.go:44 +0x68
github.com/sunny0826/kubecm/cmd.(*NamespaceCommand).Init.func1(0x1400047d900?, {0x10540d600?, 0x4?, 0x103c5e56c?})
        github.com/sunny0826/kubecm/cmd/namespace.go:32 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000654000, {0x10540d600, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x1400039e600)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        github.com/sunny0826/kubecm/main.go:30 +0x24
➜  k8ssandra git:(helm_charts) ✗
```

As you see, kubectl correctly reads the KUBECONFIG setting, but kubecm does not and tries to probably connect to somewhere which isn't running.

**To Reproduce**
Start a kind cluster with different kubeconfig & context than the default. export kubeconfig and try to run kubecm ns.

**Expected behavior**
namespaces should be listed correctly, just like kubectl works. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sunny0826** [comment]
@burmanm Thanks for your feedback, currently kubecm doesn't read settings from KUBECONFIG, it currently only reads them from the `--config` flag or `.kube/config`, this will be fixed in the future.

You can use the command `kubecm ns -config "/Users/michael.burman/projects/k8ssandra/kubeconfig"` instead.

**Comment by sunny0826** [comment]
hi @burmanm ,I'm trying to reproduce the nil pointer issue, but without the `.kube/config` file, it throws `Error: open /Users/guoxd/.kube/config: no such file or directory` instead of the _**nil pointer**_. Can you provide more information on this? Thank you very much!

**Comment by burmanm** [comment]
Hey, I didn't have non-existant ~/.kube/config:

```
➜  k8ssandra git:(helm_charts) ✗ cat ~/.kube/config 
apiVersion: v1
kind: Config
preferences: {}
➜  k8ssandra git:(helm_charts) ✗
```

If I remove the file, then it behaves like you explained. But these "empty" files are left behind after creating a kind cluster and then removing it.

**Comment by burmanm** [comment]
I guess the easiest nil-pointer avoidance would be following patch:

```patch
diff --git a/cmd/namespace.go b/cmd/namespace.go
index 09bd3c9..2e44894 100644
--- a/cmd/namespace.go
+++ b/cmd/namespace.go
@@ -41,6 +41,11 @@ func (nc *NamespaceCommand) runNamespace(command *cobra.Command, args []string)
        if err != nil {
                return err
        }
+       if len(config.Contexts) == 0 {
+               // Present only the <Exit> option
+               return fmt.Errorf("No valid context found")
+       }
+
        currentContext := config.CurrentContext
        contNs := config.Contexts[currentContext].Namespace
        namespaceList, err := GetNamespaceList(contNs)
```

That would result in:

```
➜  kubecm git:(master) ✗ target/kubecm-v0.27.0/kubecm ns
Error: No valid context found
Usage:
  kubecm namespace [flags]
```

And then separate the actual env kubeconfig location support for another PR. I didn't quickly notice if there's other commands that use the same assumption that default config always has contexts (ns is the command I use the most).

**Comment by sunny0826** [comment]
Thanks for your feedback, I indeed did not consider the situation where `~/.kube/config` exists but is empty. You have actually fixed this issue at the code level, can you submit a PR to fix this problem? Even if you do not wish to submit a PR, your contribution will be displayed in this project's README and contribute section.
You can just fix this bug; I will open a new PR for the support of env kubeconfig.

**Comment by sunny0826** [comment]
@all-contributors please add @burmanm  for bug,code
