### ISSUE TITLE
cloud add command fails, if ~/.kube/ does not exits

### ISSUE THREAD

**Issue by jkroepke** [sunny0826/kubecm#888]
**Describe the bug**
cloud add command fails, if ~/.kube/ does not exits

**To Reproduce**
1. rm -rf ~/.kube/
2. Run `kubecm cloud add`

**Expected behavior**

No error

**Screenshots**

<img width="444" alt="Bildschirmfoto 2024-02-11 um 20 17 08" src="https://github.com/sunny0826/kubecm/assets/1560587/edaf75ea-14c9-4a4e-84f4-d83627e4686e">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sunny0826** [comment]
Indeed it is a bug, a method to initialize kubeconfig should be added when ~/.kube/ does not exist.

**Comment by AdamRussak** [comment]
@sunny0826 I'll try to help here :)
I got a function doing this in my repo: https://github.com/AdamRussak/k8f/blob/575e55ebe5d7419fbee650c7203b86f222c121d8/core/core.go#L113

I think I could use it here (probably will need small adjustments

**Comment by sunny0826** [comment]
@AdamRussak Thanks

**Comment by AdamRussak** [comment]
i started working on it.
but i need to fix e2e now.. (learn whats going on first :)

 @sunny0826  if you want to see if I'm in the right direction feel free to take a look :|
 https://github.com/AdamRussak/kubecm

**Comment by sunny0826** [comment]
@AdamRussak I don't see an e2e error reported in #967, do you mean to add an e2e test for this feature?

**Comment by sunny0826** [comment]
This issue has been fixed in [v0.30.0](https://github.com/sunny0826/kubecm/releases/tag/v0.30.0).
