### ISSUE TITLE
Non-Interactive kubecm rename: `kubecm rename {existing-name} {new-name}`

### ISSUE THREAD

**Issue by bmitchinson** [sunny0826/kubecm#993]
**Is your feature request related to a problem? Please describe.**
I'd like to use `kubecm rename` in non-interactive mode so that I can add it to scripts

**Describe the solution you'd like**
Support for `kubecm rename {existing-name} {new-name}`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thanks for this tool I have several clusters and find it super help, thanks !

**Comment by sunny0826** [comment]
This is a really cool feature request. I see its worth and will definitely add it in the coming versions. It fits my plans. Thanks for the idea. It'll make the user experience better. Can't wait to make it happen!

**Comment by sunny0826** [comment]
This feature is released in [0.31.0](https://github.com/sunny0826/kubecm/releases/tag/v0.31.0)
